apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-app
    type: front-end
spec:
  containers:
    - name: nginx-containers
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
